<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TasksTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('tasks')->insert([
            [
                'title' => 'Proses onboarding karyawan baru',
                'description' => 'Siapkan daftar onboarding dan tentukan mentor',
                'status' => 'todo',
                'priority' => 'high',
                'assigned_user_id' => 3,
                'created_by' => 1,
                'due_date' => '2025-10-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Perbaiki bug login',
                'description' => 'Kesalahan saat refresh JWT pada kondisi traffic tinggi',
                'status' => 'in_progress',
                'priority' => 'urgent',
                'assigned_user_id' => 3,
                'created_by' => 2,
                'due_date' => '2025-09-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Desain halaman landing',
                'description' => 'Layout responsif untuk kampanye marketing',
                'status' => 'todo',
                'priority' => 'medium',
                'assigned_user_id' => 4,
                'created_by' => 1,
                'due_date' => '2025-10-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Backup basis data',
                'description' => 'Jadwalkan backup otomatis ke S3',
                'status' => 'todo',
                'priority' => 'high',
                'assigned_user_id' => null,
                'created_by' => 2,
                'due_date' => '2025-10-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Buat unit test',
                'description' => 'Tingkatkan coverage modul pembayaran',
                'status' => 'in_progress',
                'priority' => 'medium',
                'assigned_user_id' => 3,
                'created_by' => 2,
                'due_date' => '2025-10-20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tambahkan rate limit API',
                'description' => 'Batasi request per pengguna',
                'status' => 'todo',
                'priority' => 'medium',
                'assigned_user_id' => 5,
                'created_by' => 1,
                'due_date' => '2025-10-08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kirim survei pelanggan',
                'description' => 'Kirim survei NPS ke pelanggan terbaru',
                'status' => 'done',
                'priority' => 'low',
                'assigned_user_id' => 5,
                'created_by' => 2,
                'due_date' => '2025-09-25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Refactor modul autentikasi',
                'description' => 'Pisahkan logika autentikasi ke service class',
                'status' => 'in_progress',
                'priority' => 'high',
                'assigned_user_id' => 3,
                'created_by' => 1,
                'due_date' => '2025-10-12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Perbaiki pipeline CI',
                'description' => 'Build gagal di Node.js 20',
                'status' => 'blocked',
                'priority' => 'high',
                'assigned_user_id' => 4,
                'created_by' => 2,
                'due_date' => '2025-10-03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tambahkan lokalization',
                'description' => 'Implementasi i18n untuk bahasa Indonesia',
                'status' => 'todo',
                'priority' => 'medium',
                'assigned_user_id' => null,
                'created_by' => 2,
                'due_date' => '2025-10-30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Optimasi gambar',
                'description' => 'Gunakan format WebP dan resize otomatis',
                'status' => 'todo',
                'priority' => 'low',
                'assigned_user_id' => 4,
                'created_by' => 1,
                'due_date' => '2025-11-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Migrasi pembayaran',
                'description' => 'Pindah ke gateway pembayaran baru',
                'status' => 'in_progress',
                'priority' => 'urgent',
                'assigned_user_id' => 3,
                'created_by' => 2,
                'due_date' => '2025-10-02',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Audit aksesibilitas',
                'description' => 'Perbaiki masalah ARIA',
                'status' => 'todo',
                'priority' => 'medium',
                'assigned_user_id' => 4,
                'created_by' => 1,
                'due_date' => '2025-11-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Buat dokumentasi API',
                'description' => 'Dokumentasi referensi untuk partner',
                'status' => 'todo',
                'priority' => 'low',
                'assigned_user_id' => 5,
                'created_by' => 1,
                'due_date' => '2025-11-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Lakukan pemindaian keamanan',
                'description' => 'Jalankan SAST dan perbaiki temuan',
                'status' => 'todo',
                'priority' => 'urgent',
                'assigned_user_id' => 2,
                'created_by' => 1,
                'due_date' => '2025-09-28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
